version: '3.8'

services:

  backend:
    build: ../converter
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
